### ISSUE TITLE
bugReport : Y a quelques petits problèmes avec le défilement s...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#104]
#### content :
Y a quelques petits problèmes avec le défilement sur le forum aussi, notamment le fait que passer sur une vidéo YT intégrée stoppe de défilement (quand le curseur entre dedans) 
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/vEgHeiK2s6oXDrqcN/forum/?mainTopic=true&topicId=P75nbcKyzoSL3nTys
> size : 1760 x 856
> locale : fr-FR

**Comment by robinBanquo** [comment]
réglé :)
