### ISSUE TITLE
bugReport : Au niveau des tableurs toujours : J'ai créé 2 tabl...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#114]
#### content :
Au niveau des tableurs toujours : J'ai créé 2 tableurs. Quand je passe de l'un à l'autre tout le contenu s'efface et je ne peux pas le retrouver. J'utilise firefox. C'est peut être un bug.
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/QudECJAfpxdyHQygo/forum?spreadsheetId=WsjJF8baxj9es34yH
> size : 1366 x 622
> locale : fr-FR

**Comment by robinBanquo** [comment]
je clos le ticket vu que c'est dupliqué
