### ISSUE TITLE
petits détails sur tableur

### ISSUE THREAD

**Issue by ioqt00** [HUB-HUmanBeing/SystemD#119]
- y a un tooltip quand on passe sur le tableur dans la liste qui ne sert à rien (pas d'entrée dans le json)

- "Aucun tableur" reste quand on créé un nouveau tableur, c'est pas joli

- On doit recharger la page pour que les tableurs supprimés disparaissent

**Comment by robinBanquo** [comment]
3eme point-> c'est bon
2eme point-> facile, c'est a faire
1er point-> je crois que c'est ok, mais faudrait preciser

**Comment by robinBanquo** [comment]
le 2eme point est en prod
je crois qu'on etait bon aussi pour l'autre, je referme
