### ISSUE TITLE
bugReport : Bonjour,

j'avais généré une invitation pour 1 per...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#138]
#### content :
Bonjour,

j'avais généré une invitation pour 1 personne, et j'ai été informée que cette invitation avait expiré (avant le délai prevu, me semble-t-il). Par curiosité, j'ai utilisé le lien (expiré), qui m'a permis quand même de créer un compte. Il n'avait donc pas expiré.

Ce n'est pas très grave, j'ai donc eu l'inspiration de créer une nouvelle invitation (non expirée) pour inviter cette même personne, en espérant que c'est bien pour une personne et qu'elle n'expirera pas avant le délai prévu.

Malgré ces petits inconvénients, j'adore votre projet et j'en fait une pub terrible. Merci de ce travail (que j'imagine collossal).

J'ai une question: est-il possible de voir si les membres d'un projet sont en ligne?

Très cordialement, et Joyeux Noël et Bonne Année.
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Tablet; rv:45.0) Gecko/45.0 Firefox/45.0)
> appVersion : 5.0 (Windows)
> vendor : 
> url : https://www.system-d.org/project/JJ3GiSZLQQZqmXbAx/members
> size : 1018 x 596
> locale : fr-FR

**Comment by ioqt00** [comment]
Merci beaucoup pour vos retours, et merci pour la pub, c'est super de savoir que ça sert :) 

Avoir une idée de qui est connecté est un de nos projets, même si on ne peut donner de date au développement de la fonctionnalité... 

Concernant le problème d'expiration de l'invitation, je n'arrive pas à reproduire la situation pour le moment. Merci quand même pour le signalement, on va garder ça à l'esprit ! 

Bonne année et joyeux nöel !
