### ISSUE TITLE
suggestion : Bonjour, vous devriez mettre quelque part sur le s...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#144]
#### content :
Bonjour, vous devriez mettre quelque part sur le site l'adresse gitub, sans que l'on soit obligé de soumettre un bug ou faire une suggestion (car là elle apparait). Merci, car sauf erreur de ma part, je ne la vois pas.

**Comment by robinBanquo** [comment]
c'est en bas de la première page, dans la partie contact, mais c'est judicieux de mettre le lien aussi dans la partie bug et suggestion :)

**Comment by robinBanquo** [comment]
c'est fait :)
