### ISSUE TITLE
suggestion : Bonjour, Bravo ! Première suggestion: avoir la pos...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#146]
#### content :
Bonjour, Bravo ! Première suggestion: avoir la possibilité d'éditer un commentaire que l'on vient d'enregistrer pour le corriger ?

**Comment by robinBanquo** [comment]
ca marche, je vais essayer de faire ca bientot, ca devrais pas etre tres compliqué

**Comment by robinBanquo** [comment]
c'est fait
