### ISSUE TITLE
bugReport : Inscription buggee sur safari mobile . Bloqué à la...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#168]
#### content :
Inscription buggee sur safari mobile . Bloqué à la phase de génération des clefs
#### context info :
> platform : iPhone
> userAgent : Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1
> appVersion : 5.0 (iPhone; CPU iPhone OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1
> vendor : Apple Computer, Inc.
> url : https://www.system-d.org/login
> size : 320 x 315
> locale : fr-FR

**Comment by lapin-b** [comment]
Hello,

J'ai pu trouver un bout de réponse. Apparemment, si j'ai compris ce que j'ai pu trouver à droite et à gauche, Safari et Edge ne semble [pas apprécier qu'un paramètre manque](https://stackoverflow.com/questions/33043091/public-key-encryption-in-microsoft-edge) dans une des fonctions de crypto.

De plus, en regardant en vitesse sur [caniuse](https://caniuse.com/#search=crypto), je constate que des API de cryptographie ne sont pas supportées par Safari. C'est un test à faire et voir comment ça réagit.

Dès que j'ai un peu de temps libre, je tenterai de faire un patch et une pull request.

**Comment by robinBanquo** [comment]
je viens de tester en local sur safari mac depuis le taff et ca marche...

**Comment by lapin-b** [comment]
Donc il ne s'agit pas de paramètre manquant ?

Alors une histoire de variante mobile et desktop ? Je ne me suis pas encore tout à fait penché dessus parce que le temps.

Je vais voir si j'arrive à reproduire le bug sur une VM Windows 10 :thinking:
