### ISSUE TITLE
bugReport : Last part of the word "VERSCHLÜSSELT" which means ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#169]
#### content :
Last part of the word "VERSCHLÜSSELT" which means "CHIFFRÉE" is truncated. German has long words, so the last letter "T" is not entire. I saw the similar cosmetic effect with Safari on a Mac.
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/
> size : 1863 x 903
> locale : fr-FR

**Comment by scoid** [comment]
![Firefox_Screenshot_2020-01-05T21-16-34 669Z](https://user-images.githubusercontent.com/2099251/71786280-fb77e900-3009-11ea-8661-445de42d5974.png)

**Comment by robinBanquo** [comment]
une petite réduction de taille de police fera l'affaire, si quelqu'un est motivé, qu'il se lance, sinon je ferais ca bientot :)
