### ISSUE TITLE
bugReport : After successful registering you are welcomed in F...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#171]
#### content :
After successful registering you are welcomed in French which is nice, but should be in the native language choosen by the user; in this case German.
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/
> size : 1863 x 903
> locale : de-DE

**Comment by scoid** [comment]
![Firefox_Screenshot_2020-01-05T21-40-40 750Z](https://user-images.githubusercontent.com/2099251/71786556-d042c900-300c-11ea-93f4-78a399b65412.png)
