### ISSUE TITLE
translation of "Géneration de lien d'invitation" not possible

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#172]
**Describe the bug**
https://www.system-d.org/project/example-xyz/new-invitation
When you clicked on the button "GÉNÉRER LE LIEN D'INVITATION"

![Firefox_Screenshot_2020-01-06T09-02-57 242Z](https://user-images.githubusercontent.com/2099251/71807892-aa4d1100-306c-11ea-8d56-6965983ca65e.png)

for a very short moment you will see the message "Géneration de lien d'invitation" (no screenshot) which cannot be translated.

**Comment by ioqt00** [comment]
I will look at that, thanks for reporting
