### ISSUE TITLE
translatable tool tips for map symbols

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#174]
I would like to see on the map translateable tool tips/ info bulls for each symbol.
![Firefox_Screenshot_2020-01-06T20-18-58 044Z](https://user-images.githubusercontent.com/2099251/71846352-a2bc5500-30ca-11ea-9adb-48e9c8a682fc.png)

And the same here in the parameter menu of the map:

![Firefox_Screenshot_2020-01-06T20-59-03 731Z](https://user-images.githubusercontent.com/2099251/71848464-d057cd00-30cf-11ea-98de-614da23fba80.png)

**Comment by ioqt00** [comment]
@robinBanquo On met des tooltips là, ça me parait bien ?
