### ISSUE TITLE
translation of bug report when you are not logged in

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#182]
When the user is not logged in an wants to send a bug report, the languages are not consistent.

![Firefox_Screenshot_2020-01-07T11-34-18 470Z](https://user-images.githubusercontent.com/2099251/71893312-8dd3d600-314b-11ea-95da-65d4f8eda6dd.png)

Now change languages and you will experience a multilingual mixture.

**Comment by robinBanquo** [comment]
i think that the translation exists but it is recently added so the translation is missing, i will inspect that

**Comment by ioqt00** [comment]
Exactly, I close :)
