### ISSUE TITLE
BugReport : Suppression d'une discussion

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#187]
**Description du bug**
Lors de la suppression d'une discussion, elle reste affichée à l'écran (y compris pour les autres membres connectés). Il faut faire un refresh du browser (F5) pour la voir disparaître définitivement. Cela peut être déroutant...

**Pour reproduire**
1. Aller à Forum
2. Créer un nouveau dossier
3. Créer une nouvelle discussion
4. Ajoutez une nouvelle publication
5. Supprimer la discussion

**Comportement attendu**
La discussion supprimée devrait disparaître immédiatement.

**Environnement**
 - OS: Linux Mint 19.3
 - Browser Firefox v71.0

**Comment by robinBanquo** [comment]
bien vu !  c'est réglé
