### ISSUE TITLE
BugReport : Ajout d'une publication de type image/fichier

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#188]
**Description du bug**
Lors de l'ajout d'une publication de type "fichier", la publication ne s'affiche pas et pourtant on retrouve bien le doc. publié dans la liste des documents. Je joins une vidéo sur ce comportement "bizarre"...(url ci-dessous)

https://framadrop.org/r/12ienk4Ze7#+wEnE83WH/fiXwT7NhKjrWwQBpuuAVR7pqu0j2hUfrY=

**Pour reproduire**

1. L'Admin crée un nouveau dossier
2. L'admin crée une nouvelle discussion
3. Un membre ajoute un publication, dans cette discussion, de type texte >>> OK
4. Un membre ajoute un publication de type fichier/image >>> NOK - La publication n'apparaît pas!
5. On recommence au cas où...
6. Même problème
7. On va sur DOCUMENTS et on s'aperçoit que le fichier que l'on tentait de publier dans la discussion apparaît plusieurs fois...

**Comportement attendu**
La publication devrait s'afficher dans le fil de la discussion - Comment éviter de poster plusieurs occurrence d'un même fichier ? Gestion de version ? Message à l'utilisateur ?

**Environnement**
    OS: Linux Mint 19.3
    Browser Firefox v71.0

**Comment by Fabrice61** [comment]
J'ajoute quelques précisions :
- en "discussion principale" l'upload de fichiers fonctionne bien
- c'est dans une discussion "secondaire" (une discussion ouverte dans un nouveau dossier) que cela ne marche pas...que ce soit pour l'admin comme pour les autres membres

**Comment by robinBanquo** [comment]
merci @Fabrice61 pour l'info discussion secondaire, j'avais du mal a reproduire, ca va grave m'aider

**Comment by robinBanquo** [comment]
résolu
