### ISSUE TITLE
Platform backup

### ISSUE THREAD

**Issue by githubldvx** [HUB-HUmanBeing/SystemD#191]
**Describe the bug**
À ce jour nous ne maîtrisons pas la sauvegarde des données de la plateforme.

**Expected behavior**
Voir les offres mlab et maîtriser la sauvegarde des données (quitte à réaliser une simulation de restauration des données).

**Comment by robinBanquo** [comment]
c'est fait, j'ai pris la formule plus chere aussi, et niveau perf c'est vraiement mieux
