### ISSUE TITLE
bugReport : Salut , J'utilise System D sous Firefox et Xubuntu...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#193]
#### content :
Salut , J'utilise System D sous Firefox et Xubuntu et je rencontre deux bugs. 
Un avec les tableurs.
Quand je crée le premier tableur tout va bien . Quand j'en crée un second la colonne de gauche (discussion principale, documents, tableurs ) disparait et le tableur prend toute la largeur de la fenêtre. 
Je dois donc cliquer sur «forum» pour retrouver cette colonne et naviguer entre les deux tableurs. Quand je retourne sur le premier, les données qu'il contient ont disparues.Je vais sur le second et il est vide. Quand je supprime ces tableurs ils disparaissent mais j'ai un message qui apparait plusieurs fois  : «une erreur s'est produite»

Le second bug c'est avec les documents.
J'arrive à les télécharger via une discussion. Quand je vais dans la section «documents» et que je veux l'ouvrir, j'ai le message «téléchargement et déchiffrement du fichier» avec le symbole animé qui tourne. Mais le doc ne s'ouvre jamais.
C'est un doc odt de 20ko.
Merci et bravo pour votre travail !
Benjamin

#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/
> size : 1364 x 571
> locale : fr-FR

**Comment by robinBanquo** [comment]
les deux sont résolus !
