### ISSUE TITLE
Bug loader

### ISSUE THREAD

**Issue by ioqt00** [HUB-HUmanBeing/SystemD#194]
Le loader reste après chargement de la page dans certains cas (j'ai pas compris de logique)

**Comment by ioqt00** [comment]
Sur les pages membres et paramètres des projets, sous FF (apparement pas de problèmes sous Chromium). 

Sur la page membre, le loader reste et le rendu texte est buggé (sauf le lien pour créer une invitation qui lui est affiché correctement). Tout est chargé dans le DOM...

**Comment by robinBanquo** [comment]
j'ai encore jamais vu ce bug, des instructions pour le reproduire ?

**Comment by ioqt00** [comment]
![image](https://user-images.githubusercontent.com/54356746/72225715-ef030b80-3588-11ea-8361-21e67fea07a4.png)
Le rendu que j'ai sur FF, impossible à reproduire en local

**Comment by ioqt00** [comment]
Et dans l'onglet paramètres 
![image](https://user-images.githubusercontent.com/54356746/72225735-2bcf0280-3589-11ea-8880-fba240c402ff.png)

**Comment by robinBanquo** [comment]
merci pour les captures d'écran, je comprends mieux du coup :)
mais j'arrive tjrs pas a le reproduire, j'ai bien envi de rajouter une popup pour inviter les gens a mettre a jour leur firefox ^^
@ioqt00

**Comment by robinBanquo** [comment]
je penses que c'est résolu, réouvre @ioqt00 si tu te rends compte du contraire

**Comment by ioqt00** [comment]
Toujours là en fait, la même chose.
