### ISSUE TITLE
Problème firebase

### ISSUE THREAD

**Issue by ioqt00** [HUB-HUmanBeing/SystemD#196]
J'ai ce message:

`Error: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
`
Ma config: 

Name 	Firefox
Version 	68.3.0esr
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
OS 	Linux 4.9.0-11-amd64

Bon courage :)

**Comment by robinBanquo** [comment]
bah t'as une version de firefox un peu datée... c'est bloquant comme bug?

**Comment by ioqt00** [comment]
Je sais pas encore, mais c'est peut être lié aux problèmes de tooltips qui s'affichent pas et de loader qui traine... Je comprends pas si ça veut dire qu'elle tourne pas ou si c'est juste pas supporté.
Ma version elle est pas si datée que ça, c'est la version stable du dépôt Debian et c'est celle qui tourne sous Android.

**Comment by robinBanquo** [comment]
cette érreur va rester à priori, et il faudra peut etre annoncer que le navigateur est trop vieux ...

**Comment by robinBanquo** [comment]
les notifs sont débuggées elles par contre !!

**Comment by robinBanquo** [comment]
je le close du coup vu que c'est juste une histoire de version de ff qui supporte pas les notifs firebase et que je peux pas y faire grand chose et que ca pose pas de problemes
