### ISSUE TITLE
Amélioration : Lors de l'ouveture d'une discussion, se positionner en haut de la liste

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#198]
**Describe the solution you'd like**
Lorsque l'on ouvre une discussion (principale ou secondaire), la discussion s'affiche sur un post un peu au hasard et il faut scroller systématiquement vers le haut pour faire un nouveau post ou voir les posts les plus récents. Il serait préférable d'afficher la liste depuis le haut.

**Additional context**
Comportement observé sur Firefox/Linux et Chromium/Linux.

**Comment by robinBanquo** [comment]
done

**Comment by Fabrice61** [comment]
Je viens d’effectuer des tests (Linux Mint 19.3 + FF 72.0.1) et le PB ne semble pas résolu... Voir petite vidéo [ici](https://framadrop.org/r/3wp6ufGomM#K/aiHJQkzKJw8tYUSWVNvgIVRhI3FKxXl28POt9Lgks=).
