### ISSUE TITLE
Amélioration : "Sécuriser" les suppressions

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#199]
**Describe the solution you'd like**

Lorsque l'on supprime, un projet, un dossier, une discussion ou un document, cette suppression est irréversible et je pense qu'une double confirmation serait souhaitable, du style : 

- êtes-vous sûr de vouloir supprimer le projet NOM_DU_PROJET de manière irréversible ?
ou bien
- êtes-vous sûr de vouloir supprimer le dossier NOM_DU_DOSSIER de manière irréversible ?
ou bien
- êtes-vous sûr de vouloir supprimer la discussion NOM_DE_LA DISCUSSION de manière irréversible ?
ou bien
- êtes-vous sûr de vouloir supprimer le document NOM_DU_DOCUMENT de manière irréversible ?

Cette double confirmation pourrait-être activée par défaut pour tous les utilisateurs et un utilisateur pourrait désactiver cette double confirmation via ses paramètres personnels.

**Comment by githubldvx** [comment]
Je pense que ce ticket a été traité car j'ai des messages d'avertissements :

![image](https://user-images.githubusercontent.com/16150810/72936241-b5878880-3d5e-11ea-8069-3227d603f298.png)

![image](https://user-images.githubusercontent.com/16150810/72936309-cfc16680-3d5e-11ea-8807-e631bcb0223e.png)

![image](https://user-images.githubusercontent.com/16150810/72936368-f54e7000-3d5e-11ea-923c-bc150ff1f81e.png)

![image](https://user-images.githubusercontent.com/16150810/72936198-9c7ed780-3d5e-11ea-8910-f3314d56ffa7.png)

@Fabrice61 : c'est bon pour vous ?

**Comment by Fabrice61** [comment]
Impec!
