### ISSUE TITLE
bugReport : donner les droits d'admins ne fonctionne plus...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#200]
#### content :
donner les droits d'admins ne fonctionne plus
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
> appVersion : 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/tQ9N5oLtNbLbhteQJ/members
> size : 930 x 911
> locale : fr-FR

**Comment by ioqt00** [comment]
Je viens de reset jusqu'à mon arrivée sur le projet pour tenter de comprendre quand le problème apparaissait. Jusque là, j'ai pas trouvé de commit où ça marche comme on veut (même si on est admin, seul le premier admin peut créer des dossiers, etc.).
Donc, soit ça n'a jamais marché (ce qui me donne un peu l'impression d'être fou), soit c'est un problème avec le versioning de meteor et des paquets qui ne sont pas dans le git. Ça me paraît encore plus fou.

**Comment by ioqt00** [comment]
dans les commits plus vieux, j'ai pu reproduire et résoudre en commentant la NotifPush l.96 du ProjectMemberMethods.js.
Toujours pas trouvé la maj qui a pu mettre le bordel dans les commits récents...

**Comment by robinBanquo** [comment]
résolu :p
