### ISSUE TITLE
string "Aucun événement à afficher" not translateable

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#202]
The string "Aucun événement à afficher" in https://www.system-d.org/project/example-xyz/calendar is not yet translateable.

![Firefox_Screenshot_2020-01-11T20-36-06 543Z](https://user-images.githubusercontent.com/2099251/72210386-dc220580-34ba-11ea-8f73-5cea502525e8.png)

**Comment by robinBanquo** [comment]
i'm on it, it will be  translatable

**Comment by scoid** [comment]
Merci ;-)
