### ISSUE TITLE
bugReport : il ne se passe rien quand je clique sur "paramètre...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#203]
#### content :
il ne se passe rien quand je clique sur "paramètre" dans agenda 
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
> appVersion : 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/TEZZjNukmH42DNbeL/calendar?time=-3&side=calendarSettings&view=days
> size : 1366 x 625
> locale : fr-FR

**Comment by robinBanquo** [comment]
c'est parce que le bouton parametre permet d'ouvrir le panneau parametre tjrs ouvert par défaut.je vais faire en sorte que le bouton ne s'affiche que quant c'est nécessaire.
