### ISSUE TITLE
bugReport : Merci pour cet outil génial ! 
Défaut d'affichage ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#205]
#### content :
Merci pour cet outil génial ! 
Défaut d'affichage de l'agenda aujourd'hui, sur la totalité des projets: le menu de droite apparaît mais pas l'agenda en lui même, à la place tourne sans fin le "sablier". J'ai tenté la déco/reco, suppression du cache de firefox, rien n'y fait... 
Merci encore.
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/f3RuMHo8v8eRZ3TGY/calendar
> size : 1366 x 642
> locale : fr-FR

**Comment by robinBanquo** [comment]
oups, on dirait que mon débug d'hier a tout cassé ^^
je vais revert ca dès ce soir

**Comment by robinBanquo** [comment]
j'ai essayé un truc, je comprends pas bien comment le reproduire...

**Comment by bstn-chmpns** [comment]
Ok, mince ! Ça touche tout le monde ?

J'espère qu'une solution va s'offrir à toi bientôt ! 
C'est assez handicapant, surtout quand ça tombe le jour où j'ai enfin réussi à motiver les copains à sortir un peu de fb pour gérer l'asso !! Je les vois déjà avec leur "ouais, tes solutions et logiciels indé blabla, ça fonctionne pas...!"
Bref, quoiqu'il en soit, je saurais quoi leur répondre ;)

Merci encore pour cet outil d'enfer, et je croise les doigts pour que le problème soit résolu sans que ça t'en coute trop... 

Bon courage !

ps: je n'ai absolument aucune connaissance en code... je ne peux pas aider là dessus...

**Comment by robinBanquo** [comment]
ha zut, j'ai fait une tentative de débuggage qui n'a pas fonctionné on dirait.
je m'occupe de ce bug ce soir, si tu veux pouvoir acceder quand meme au calendrier pour la démo avec tes potes, change deux fois de langue et c'est bon.
désolé pour les bugs,c'est encore une béta, et on peut s'en occuper qu'a coté du travail, pas suffisament a notre gout ^^

**Comment by bstn-chmpns** [comment]
Ne sois pas désolé pour les bugs, on sait que c'est un travail en cours, non rémunéré fait à côté du boulot "de la vraie vie" !! 
On saura patienter (et mettre la main au porte-monnaie à un moment donné !!)
Vivement ce soir (ça fera comme un cadeau au pied du sapin !) et bonne journée !

Par contre, pour info, changer deux fois de langue n'a aucun effet sur l'agenda chez moi...

**Comment by robinBanquo** [comment]
arg zut, désolé, il faudra attendre ce soir, je fait ca dès que j'arrive

**Comment by robinBanquo** [comment]
resolu

**Comment by bstn-chmpns** [comment]
Merci 1000 fois !!!
