### ISSUE TITLE
BugReport : Publication de type "fichier"

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#210]
**Describe the bug**
Les publications de type "Fichiers" ne fonctionnent plus bien, en fait l'upload se fait bien mais quand on publie le post, il n'y a plus d’icône symbolisant le fichier...

![Capture du 2020-01-15 22-14-19](https://user-images.githubusercontent.com/59598652/72472386-c37c5d00-37e4-11ea-8583-d26820a13da0.png)

**To Reproduce**
1. Go to 'Nouvelle publication'
2. Click on 'publication de type fichiers'
3. Glisser un fichier (ici un fichier PNG de 23,4Ko)
4. Publiez
5. Le post ne contient pas l'icone

**Expected behavior**
Le post doit contenir l'icone pour que l'on puisse cliquer dessus et consulter ou télécharger le fichier...

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser FF v72.0.1

**Comment by robinBanquo** [comment]
dupliqué #188
