### ISSUE TITLE
icon not in line with text "SUPPRIMER"

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#219]
=
![Firefox_Screenshot_2020-01-17T10-03-24 078Z](https://user-images.githubusercontent.com/2099251/72603369-ca07f300-3910-11ea-95c3-24faa07cd274.png)

**Comment by robinBanquo** [comment]
you are demoniac @scoid ^^

**Comment by scoid** [comment]
@robinBanquo I know it's nitpicking in the face of important bugs, but it does help confidence in the platform to test it for longer in the first place.
