### ISSUE TITLE
Le bouton "SUPPRIMER" n'a aucun effet pour supprimer le dialogue.

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#226]
1) Le bouton "SUPPRIMER" n'a aucun effet pour supprimer le dialogue.
Le mot "test" que j'ai écrit, je ne peux pas le supprimer.

2.) L'affichage multiple de deux poubelles comme symbole pour 2 fichiers supprimés est irritant.
![Firefox_Screenshot_2020-01-19T17-42-05 781Z](https://user-images.githubusercontent.com/2099251/72685590-82859080-3ae3-11ea-862e-bfa93d24e49b.png)

72.0.1 (64-Bit) Firefox, Ubuntu

**Comment by ioqt00** [comment]
Ha j'avais pas vu, il faut aussi rajouter un bouton annuler. (Et c'est vrai que cette poubelle est très aggressive).
I'm on it, the "test" string can be removed with the 'edit' link, which is hidden by the "delete" button...
