### ISSUE TITLE
"NUOVO PROGETTO" out of the box in Italian

### ISSUE THREAD

**Issue by scoid** [HUB-HUmanBeing/SystemD#242]
=
72.0.1 (64-Bit) Firefox, Ubuntu

![Firefox_Screenshot_2020-01-22T07-55-54 785Z](https://user-images.githubusercontent.com/2099251/72875878-21c9a400-3ced-11ea-9b78-576113594f5f.png)

**Comment by robinBanquo** [comment]
i've seen that just by reducing padding-right it works fine

**Comment by robinBanquo** [comment]
done
