### ISSUE TITLE
suggestion : Jouer avec scrollbar color sur Firefox...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#249]
#### content :
Jouer avec scrollbar color sur Firefox

**Comment by robinBanquo** [comment]
c'est pour permettre de débugger tout les soucis de scrollbars, ca permettrait de simplifier et de ne plus avoir a utiliser de plugins lourds pour faire ca

**Comment by ioqt00** [comment]
Ok je viens de vraiment réaliser l'étendue de l'absurdité de la guerre de la scrollbar.
Le problème c'est que le scrollbar-color est expérimental sous FF est qu'il est buggé. Sous FF 72, impossible de colorer la piste, seulement les coins. 

Tu veux virer la beautify scrollbar et tant pis ? Ou on attend que Mozilla soient moins cons ?
