### ISSUE TITLE
rendre possible l'export et l'import des datas du calendar au format ics

### ISSUE THREAD

**Issue by robinBanquo** [HUB-HUmanBeing/SystemD#252]
rendre possible l'export des datas du calendar 
ya une peut etre une piste avec ca :
https://github.com/fullcalendar/fullcalendar/issues/3692
ils disent qu'il faut passer par la : https://github.com/adamgibbons/ics
et utiliser ca : https://fullcalendar.io/docs/v3/clientEvents

**Comment by robinBanquo** [comment]
deux mails à ce sujet:

Re-bonjour,
On a réussi à s'en sortir avec l'agenda. Mais une nouvelle question émerge : comment exporter l'agenda pour pouvoir le diffuser ?
Merci à toi.
Cordialement,
Quentin.

et

Bonsoir Robin,
Etudiante à l’Université de Paris 3 et dans le cadre de la mobilisation contre les réformes des retraites et de la LPPR j’aimerais pouvoir exporter l’agenda de nos réunions en former pdf ou autre. Cela est-il possible ?
Merci pour ton temps.
Respectueusement
Maëlle

je suis sesible a l'argument lutte et du coup je me met sur l'import-export en ics des agenda

**Comment by Yaroster** [comment]
ça fait quelques années je suis a la Sorbonne mais est-ce que ce probleme est reglé ? Ca me permetterait d'exporter mon emploi du temps
