### ISSUE TITLE
bugReport: Problème Import ICS (Calendrier)

### ISSUE THREAD

**Issue by Fabrice61** [HUB-HUmanBeing/SystemD#269]
Les structures simples ICS (ex. test5.ics attaché à ce ticket) s'importent correctement dans l'Agenda mais pas les structures plus complètes (ex. test4.ics attaché à ce ticket).

Pour résumer : 

- test5.ics s'importe correctement dans l'Agenda de System-D
- test4.ics ne s'importe pas, il ne se passe rien à l'écran, pas de message d'erreur

NB: test4.ics s'importe correctement sur un Agenda Gmail, Zimbra ou OX-App.

[test.zip](https://github.com/HUB-HUmanBeing/SystemD/files/4144819/test.zip)

**Comment by ioqt00** [comment]
#270
