### ISSUE TITLE
Password should be sent in POST not in GET

### ISSUE THREAD

**Issue by Framartin** [HUB-HUmanBeing/SystemD#28]
It's important to send login and account creation data in POST method and not in GET, in order to not send the password in the URL. The main problem is that the password will be saved in the browser history.

*How to reproduce*

1. Type you login information in the forn and validate
2. You are redirected to `<URL>?username=test&password=test`

**Comment by J3m5** [comment]
Hello and thank you for your bug report, we will look after it as soon as possible.

**Comment by robinBanquo** [comment]
Projet rebooté
