### ISSUE TITLE
suggestion : Bonjour , au niveau des notifications, j'ai juste ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#290]
#### content :
Bonjour , au niveau des notifications, j'ai juste «vous avez une réponse à un de vos messages » qui s'affiche. Mais ça ne me dit pas dans quel dossier se trouve cette réponse ou à quel message elle s''adresse. Coomme j'ai beaucoup de dossiers ce n'est pas facile de tout suivre. Merci à vous .

**Comment by robinBanquo** [comment]
désolé, c'est lié au chiffrement des contenu, le serveur (qui envoie les notifications) ne peut savoir le contenu ou la localisation des messages entrainant des notifs. du coup les notifications sont affichées de manière un peu lacunaires
