### ISSUE TITLE
bugReport : Bonjour et merci pour votre outil de grande qualit...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#297]
#### content :
Bonjour et merci pour votre outil de grande qualité.
Sur cet onglet, je ne peux pas descendre le curseur pour visualiser tous les documents, je ne sais pas s'il n'y a que moi (créateur du projet), ou si le problème persiste pour tout le monde, pouvez vous m'éclairer ? 
Merci !! :)
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
> appVersion : 5.0 (Windows)
> vendor : 
> url : https://www.system-d.org/project/ME25tW6CyXw5joEct/forum?files=true
> size : 1536 x 701
> locale : fr-FR

**Comment by robinBanquo** [comment]
merci pour le report ! c'est fixé
