### ISSUE TITLE
suggestion : Bonjour, 
Merci pour cette plateforme extraordinai...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#298]
#### content :
Bonjour, 
Merci pour cette plateforme extraordinaire !!! Elle est particulièrement utile en cette période de confinement.
Y a t-il un moyen de monter le nombre de participant pour faire des projets ayant plus de personnes impliquées ?

**Comment by robinBanquo** [comment]
oui, le nombre de particippant a un projet n'est limité que par les capacité du device a supporter les opérations de chiffrement/déchiffrements de la liste des membres du projets a priori, et on a pas encore d'idée de ou se trouve cette limite
