### ISSUE TITLE
suggestion : Bonjour, Serait il possible de sélectionner et d u...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#300]
#### content :
Bonjour, Serait il possible de sélectionner et d uploader plusieurs fichiers a la fois ? Ainsi que d intégrer un zoom dans l aperçu des documents Jpeg ? Merci

**Comment by robinBanquo** [comment]
pour l'upload multiple de fichiers c'est déja possible, mais une amélioration prochaine portera sur la partie cloud/ document des projet pour que ce soit plus pratique de partager/trier des documents
pour la preview zoomable, je viens de le faire, merci pour la suggestion
