### ISSUE TITLE
suggestion : Bonjour, 
L'agenda est très utile.
Est-il prévu d'...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#302]
#### content :
Bonjour, 
L'agenda est très utile.
Est-il prévu d'intégrer une récurrence autre qu'hebdomadaire ? exemple : Répéter une réunion chaque 1er lundi du mois, chaque 19 du mois etc... ce serait très utile sur les projets de longue durée.

Belle journée à vous et merci !

**Comment by robinBanquo** [comment]
je suis désoolé, il vous faudra les positionner manuellement, en effet, le plugin utilisé ne permet pas de faire cela.
d'autre part j'ai des doute qu'on puisse proposer une interface simple et intuitive pour pouvoir ammener un utilisateur a selectionner "tout les 2emes vendredis du mois", il me semble que ca alourdirait bcp l'interface et que le résultat serait moins simple qu'a l'heure actuelle
