### ISSUE TITLE
bugReport : Tracer un rond sur la carte bugue.
Le curseur se b...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#308]
#### content :
Tracer un rond sur la carte bugue.
Le curseur se bloque en mode croix, et on ne peut plus annuler ou ajouter d'autres formes.
Il faut quitter le mode carte et revenir pour être débloqué.
#### context info :
> platform : MacIntel
> userAgent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
> appVersion : 5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
> vendor : Apple Computer, Inc.
> url : https://www.system-d.org/project/8HPR2T9hD7Paxubvr/maps
> size : 1366 x 680
> locale : fr-FR

**Comment by robinBanquo** [comment]
la création de cercle se fait en draggant depuis le centre du cercle, j'ai fait en sorte d'annuler la création si le drag ne s'est pas effectué correctement
