### ISSUE TITLE
bugReport : Bonjour, depuis une semaine environ je n'arrive pl...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#316]
#### content :
Bonjour, depuis une semaine environ je n'arrive plus à déposer ou télécharger des documents. Le sablier tourne et rien ne se passe. 
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/QudECJAfpxdyHQygo/forum?categoryId=7ckhpv1ohsf&topicId=oS7PpGSFQ5fRRWtdr
> size : 1366 x 603
> locale : fr-FR

**Comment by robinBanquo** [comment]
souci lié au certificat https du serveur d'image, réglé
