### ISSUE TITLE
suggestion : Bonjour et merci pour votre initiative! Je teste c...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#318]
#### content :
Bonjour et merci pour votre initiative! Je teste ce matin pour la première fois System-D, et la première chose qui me manquerait serait une zone de prise de note pour chaque tâche (pour stocker quelques instructions, détails, liens et contacts en lien avec la tâche et la checklist). Cela permettrait de ne pas avoir à gérer ces notes en dehors de l'interface.
Merci!

**Comment by robinBanquo** [comment]
vous avez la partie détail de la tache qui est prévue pour cela. je ferme le ticket mais je suis ouvert aux proposition pour reflechir a comment rendre cela pplus pratique
