### ISSUE TITLE
suggestion : Seconde suggestion : le volet de consultation et d...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#319]
#### content :
Seconde suggestion : le volet de consultation et d'édition d'une tâche est assez petite, sur un écran de portable mais aussi sur un grand écran. Ainsi un élément de checklist qui fait plus de quelques mots n'est pas lisible en entier. Il me semble que doubler au moins sa largeur rendrait son ergonomie plus efficace sans géner le reste du site (puisqu'il faut de toute façon fermer ce volet pour retourner travailler dans la liste des tâches).

**Comment by robinBanquo** [comment]
ca risque de gener l'affichage de l'agenda, je ne suis pas sur que ca passe... je vais cependant faire en sorte que le texte des checklist ne soit pas coupé lors de l'affichage

**Comment by robinBanquo** [comment]
c'est fait, ca sera disponible au prochain déploiement
