### ISSUE TITLE
suggestion : Salutations camarades,
Dans le cadre de l'organisa...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#321]
#### content :
Salutations camarades,
Dans le cadre de l'organisation d'un projet sous forme collaborative, l'utilisation d'un gantt peut être extrêmement utile car il permet de mettre en vrac les tâches en voyant la cohérence dans l'enchainement des tâches. Les dates butoirs de ces tâches permettront aussi de visualiser sur l'agenda s'il y a un encombrement d'actions à un moment donné ou pas. 
Je ne sais pas ce que ma suggestion vaut mais je propose donc d'ajouter un gantt pour compléter le suivi  des tâches.
Amicalement,
Amir

**Comment by robinBanquo** [comment]
il y a un plugin payant sur l'outil de calendrier qu'on utilise dans system-d.org qui gere l'affichage sous forme de diagramme de gant mais vu nos finances ca va pas etre possible, ca coute   480 € soit un rsa ^^

du coup a moins d'une enorme générosité de tout les donnateurs ca risque d'etre compliqué :p 

par contre on pourrais dévelloper un module complémentaire permettant d'afficher les items sous la forme d'un diagramme de gant nous meme, ca parrait pas super compliqué a réaliser... cela dit je penses que d'autres priorités vont passer avant malheureusement, et j'ai du mal a pouvoir annoncer une date pour l'option "gantt" dans l'agenda du projet

**Comment by robinBanquo** [comment]
je réouvre pour pas perdre la suggestion
