### ISSUE TITLE
suggestion : Dans le tableur, ne serait-il pas plus cohérent d'...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#322]
#### content :
Dans le tableur, ne serait-il pas plus cohérent d'échanger les icônes importer et exporter ? On s'attend à ce que la flèche vers le bas serve à télécharger... Dans tous les cas, bravo pour le travail accompli !

**Comment by robinBanquo** [comment]
bien vu, je viens de régler ca
