### ISSUE TITLE
suggestion : En préambule, les reseaux sociaux ne diffusent que...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#324]
#### content :
En préambule, les reseaux sociaux ne diffusent que très d'infos par au nombre d'abonnés , en moyenne c'est 10% et maximisé à 20% ou en sandboxant un groupe, une pers avec une  info importante etc. Il y a quelques années j'avais trouvé un outils de propagations de messages hors RS et neutralisant leurs algorithmes restrictifs . Il tenait compte uniquement de la situation géographique des adresses IP. C'est à la limite du virus mais ce n'est dangereux . si mes souvenirs sont bons c'est un programme chinois ou indien ou même coréen.  D'après ce que j'avais compris comme il prenait en compte que l'IP ça devait se retrouver sous forme de notifs bureau (tout en passant les parefeux) Seulement après un crash impossible de me souvenir ou même de récupérer la moindre infos. De ce que je m'en souviens c'est un logo comme suit : boule noire avec picôts longs tordus sur fond jaune. Si ça peut inspirer quelqu'un dans une recherche ça m'aiderai car je n'arrive pas à le retrouver. Merci d'avance.

**Comment by robinBanquo** [comment]
j'ai pas tout compris, je ferme pour l'instant mais n'hésitez pas a réouvrir le ticket si vous souhaite ajouter des precisions a votre suggestion
