### ISSUE TITLE
suggestion : Bonjour,
Ce serait super de pouvoir exporter les d...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#325]
#### content :
Bonjour,
Ce serait super de pouvoir exporter les données pour les réimporter dans un Système-D hébergé sur un autre serveur.
Aussi, faire un lien dynamique avec un logiciel de calendrier serait un réel plus.
Merci pour votre super boulot, j'adore ce projet.
Bonne continuation

**Comment by robinBanquo** [comment]
bonjour, 
pour ce qui est de la premiere demande ca parrait compliqué a faire mais pas impossible, je recommande aux personnes motivées  pour rendre ca possible de me contacter pour discuter ensemble sur le comment, et j'aurais plaisir a merger leurs merge request. (je part du principe que si elles ont la compétence de faire tourner systemD sur un autrer serveur elles ont la compétence de créer cette fonctionalité).
de plus, systemD a été concu comme un outil "centralisé", et j'envisage de faire en sorte cette année de décentraliser son fonctionnement sous la forme d'une fédération de serveurs communiquant entre eux. j'avoue ne pas etre motivé pour participer aux aménagements nécessaires a ceux qui veulent heberger eux memes leurs données avant d'avoir réussi a implémenter un fonctionnement fédéré entre les differentes instances. je suis par contre super preneur des coups de mains dans la conception et la réalisation d'une déceentralisation de systemD.
un lien dynamique avec un logiciel de calendrier est problématique puisque il viole le principe de chiffrement end to end de toutes les données présentes sur la plateforme, et j'ai envie de maintenir cela comme tel.
au plaisir de discuter plus en profondeur du sujet via l'adresse mail ou sur le chat du projet figurant en bas de la page de présentation du site,
bonne journée a vous
