### ISSUE TITLE
suggestion : Bonjour à toute l'équipe. Super outil. Est il poss...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#333]
#### content :
Bonjour à toute l'équipe. Super outil. Est il possible de développer un système de récurrence une fois par mois ?  D'autre part quand on crée une nouvelle tache ce serait super de pouvoir la "placer" sur l'agenda depuis l'espace taches. Cela évite de devoir faire l'action de création de la taches deux fois. Merci pour tout! Anaïs

**Comment by robinBanquo** [comment]
bonjour, le plugin utilisé ne permet pas de faire ce genre de récurence malheureusement
