### ISSUE TITLE
bugReport : Bonjour, 
Je découvre au fur et a mesure System D ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#342]
#### content :
Bonjour, 
Je découvre au fur et a mesure System D et je trouve ça très bien. Bravo.
Cependant, dans le forum, dans l'onglet texte, on ne peut voir que 3 des textes écris. Un 4e ne sera visible et il faudra détruire un des textes présents pour y accéder. Il doit manquer une glissière à la fenêtre. Firefox80.2.03/ OsX10.15.7
#### context info :
> platform : MacIntel
> userAgent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
> appVersion : 5.0 (Macintosh)
> vendor : 
> url : https://www.system-d.org/project/cGN8H6QaBti8hqD8T/forum?padId=iqbjeem9B4x3eiGZv
> size : 1128 x 775
> locale : fr-FR

**Comment by robinBanquo** [comment]
merci pour l'info, je vais corriger cela prochainement :)

**Comment by robinBanquo** [comment]
c'est corigé et ca sera déployé très bientot
