### ISSUE TITLE
bugReport : on peut plus agrandir les images depuis le forum...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#343]
#### content :
on peut plus agrandir les images depuis le forum
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
> appVersion : 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/7SR2raDij7BMjbP8A/forum
> size : 1920 x 936
> locale : fr-FR

**Comment by robinBanquo** [comment]
réglé
