### ISSUE TITLE
bugReport : le dernier commentaire est toujour focus quant on ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#345]
#### content :
le dernier commentaire est toujour focus quant on ouvre une conversation
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
> appVersion : 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
> vendor : Google Inc.
> url : http://localhost:3000/project/jJadya8xbZ78M4TAn/forum/?categoryId=imtvcg085a&topicId=9t4X5RdHE2daRWfD9
> size : 1281 x 936
> locale : fr-FR

**Comment by robinBanquo** [comment]
fixed
