### ISSUE TITLE
bugReport : Le bouton du menu est décalé...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#347]
#### content :
Le bouton du menu est décalé
#### context info :
> platform : Linux armv8l
> userAgent : Mozilla/5.0 (Linux; Android 7.1.2; Action-X3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Mobile Safari/537.36
> appVersion : 5.0 (Linux; Android 7.1.2; Action-X3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Mobile Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/
> size : 360 x 319
> locale : en-US

**Comment by robinBanquo** [comment]
fixed
