### ISSUE TITLE
bugReport : Bonjour, je crée un nouveau projet, System-D trava...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#373]
#### content :
Bonjour, je crée un nouveau projet, System-D travaille sur "connexion chiffrée au projet" sans fin... je me déconnecte, mais ne peux pas me connecter au nouveau projet, ni le recréer.
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
> appVersion : 5.0 (Windows)
> vendor : 
> url : https://www.system-d.org/new-project
> size : 1920 x 938
> locale : fr-FR

**Comment by robinBanquo** [comment]
résolu
