### ISSUE TITLE
bugReport : Même problème sous Chrome...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#374]
#### content :
Même problème sous Chrome
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
> appVersion : 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/new-project
> size : 1920 x 969
> locale : fr-FR

**Comment by robinBanquo** [comment]
résolu
