### ISSUE TITLE
bugReport : Impossible de créer un projet, bloque à connexion ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#375]
#### content :
Impossible de créer un projet, bloque à connexion chiffré
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/new-project
> size : 1366 x 638
> locale : fr-FR

**Comment by robinBanquo** [comment]
résolu
