### ISSUE TITLE
bugReport : Bonjour,
La création de projet reste bloquée indéf...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#376]
#### content :
Bonjour,
La création de projet reste bloquée indéfiniment sur l'étape "Connexion chiffrée au projet".
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
> appVersion : 5.0 (Windows)
> vendor : 
> url : https://www.system-d.org/new-project
> size : 1920 x 938
> locale : fr-FR

**Comment by robinBanquo** [comment]
c'est résolu, merci pour l'info
