### ISSUE TITLE
bugReport : quant on clique sur la notif "commentaire suite a ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#58]
#### content :
quant on clique sur la notif "commentaire suite a un de vos messages" ca pointe pas sur le topic et ca affiche du noir

#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
> appVersion : 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/LjGhnwPGWjvurZR3X/forum?categoryId=undefined&topicId=HvyuH5RLA2uyR2oKx
> size : 1920 x 937
> locale : fr-FR

**Comment by robinBanquo** [comment]
c'est réglé
