### ISSUE TITLE
bugReport : Après suppression d'un projet, il apparait toujour...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#59]
#### content :
Après suppression d'un projet, il apparait toujours dans le menu. Si je veux me rendre dessus, il bloque sur le loading du déchiffrement
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/W8XLQJfzMcq8XFFJ2/forum
> size : 1920 x 924
> locale : en-US

**Comment by robinBanquo** [comment]
ca le fait pas chez moi, ni en local, ni en prod...

**Comment by ioqt00** [comment]
Ça vient de me le refaire, je vais fouiller un peu

**Comment by ioqt00** [comment]
J'ai désormais 3 fantômes de projets dans ma liste. Tu pourrais aller voir si y a des indices au niveau de la DB ? J'imagine que les problèmes sont liées mais j'ai aussi des projets qui disparaissent de la liste, ce qui est beaucoup plus embétant...

**Comment by ioqt00** [comment]
Ils s'appellent "la morge wesh" et "sqdfghjklkjhgfdsq"

**Comment by refloat** [comment]
Je pense que ca le fait sur firefox et pas sur chromium.
A verifier.

**Comment by ioqt00** [comment]
Bug reproduit sous mozilla en local. Le projet est bien supprimé de la DB, mais il reste dans le dict de session.

**Comment by ioqt00** [comment]
Ainsi que dans les dans le user.private. Ça arrive ~1 fois sur 5, est ce que quelqu'un pourrait refaire le test sous Chromium pour confirmer que c'est un problème seulement sur FF ?

**Comment by ioqt00** [comment]
Le problème sur Firefox c'est que l'ordre dans Session.projects arrête pas de change. À la suppression, l'index dans Session.projects diffère de l'index dans User.private.projects, et il vire le mauvais projet de la liste. 
Deux choix :
1° Aller chercher l'index dans users.private direct
2° Comprendre pourquoi les projets se baladent comme ça sur FF

**Comment by ioqt00** [comment]
Le async lors du décryptage (l.496 du cryptoTools) ne fonctionne pas sur Firefox, donc c'est pas séquentiel, donc ça fout le bordel. Si je rajoute un console.log l.499 c'est ok. Mes compétences limitées me propose de m'arrêter là pour le moment.

**Comment by robinBanquo** [comment]
merci pour les infos, je vais jeter un oeuil avec a en tete

**Comment by robinBanquo** [comment]
Le bugfix est pushé sur master, testé sur Firefox et Chrome, mais j'aimerais des tests complémentaire avant de mettre en prod, c'est un peu trop critique pour faire les sauvages
