### ISSUE TITLE
bugReport : Problèmes lors de l'écriture des tâches dans un év...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#65]
#### content :
Problèmes lors de l'écriture des tâches dans un évènement : des lettres se supprimes et se rajoutent aléatoirement, et le curseur voyage entre la zone de texte pour rajouter une tâche et le titre de la liste de tâches.
#### context info :
> platform : MacIntel
> userAgent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
> appVersion : 5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
> vendor : Apple Computer, Inc.
> url : https://www.system-d.org/project/Ch67km9QrdoKEEbMc/forum
> size : 1428 x 793
> locale : fr-FR

**Comment by robinBanquo** [comment]
c'est réglé
