### ISSUE TITLE
bugReport : besoin d actualiser la poge apres une creation de ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#68]
#### content :
besoin d actualiser la poge apres une creation de projet sur firefox

#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/XBMWyK9gNPRuphdwH/params
> size : 1600 x 899
> locale : fr-FR

**Comment by robinBanquo** [comment]
mince, j'arrive pas à reproduire, ni sur le site en prod, ni en local...

**Comment by ioqt00** [comment]
Je vais essayer de comprendre d'où ça peut venir, j'ai le problème très régulièrement quand je change de template aussi

**Comment by robinBanquo** [comment]
ouais, moi j'arrive pas a reproduire, j'ai pas ce genre de soucis sur mon firefox...
@ioqt00

**Comment by ioqt00** [comment]
@robinBanquo T'as quelle version de Firefox ? Tu le fais
 tourner sur Windows ?

**Comment by robinBanquo** [comment]
non, sur linux mint 19 (ubuntu 18.04 du coup je crois)

**Comment by ioqt00** [comment]
Et ta version de firefox ? Si quelqu'un a des infos en plus je suis preneur, perso ça me fait ça à chaque fois que je tente de retourner au 'home' et à chaque fois que je change de projet.
