### ISSUE TITLE
bugReport : La tooltips "tout supprimer" des notifs reste au m...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#70]
#### content :
La tooltips "tout supprimer" des notifs reste au milieu de l'écran
#### context info :
> platform : Linux armv8l
> userAgent : Mozilla/5.0 (Linux; Android 7.1.2; Action-X3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
> appVersion : 5.0 (Linux; Android 7.1.2; Action-X3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/LjGhnwPGWjvurZR3X/tasks
> size : 360 x 263
> locale : fr-FR

**Comment by robinBanquo** [comment]
resolu
