### ISSUE TITLE
bugReport : Pas de téléchargement d'image d'avatar (profil ou ...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#71]
#### content :
Pas de téléchargement d'image d'avatar (profil ou projet). Format(s) acceptés?
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
> appVersion : 5.0 (Windows)
> vendor : 
> url : https://www.system-d.org/user-params
> size : 1920 x 1075
> locale : fr-FR

**Comment by robinBanquo** [comment]
résolu, pb de certificats ssl du serveur d'assets
