### ISSUE TITLE
bugReport : La pop up d'info disant d'accepter les notificatio...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#74]
#### content :
La pop up d'info disant d'accepter les notifications du browser n'arrête pas d'apparaître, sans possibilité de la fermer. Obligé d'attendre 10/15 seconde à chaque moi. C'est embêtant.
Capture ici : https://www.dropbox.com/s/xdpvpndf41gl61i/Screenshot%202019-11-11%20%C3%A0%2015.38.20.png?dl=0
#### context info :
> platform : MacIntel
> userAgent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15
> appVersion : 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15
> vendor : Apple Computer, Inc.
> url : https://www.system-d.org/project/MyKZuNz2WaFtmHFdq/members
> size : 2560 x 1329
> locale : fr-FR

**Comment by robinBanquo** [comment]
probleme d'incompatibilité Safari, dans l'urgence un bandeau a été rajouté afin d'informer les utilisateurs qu'on est pas au point la dessus et que l'experience est meilleure sur chrome

j'arrive pas a installer safari sur mon linux pour regler cela en local, du coup
BESOIN D'AIDE DE LA PAR D'UN DEV MAC/SAFARI

**Comment by robinBanquo** [comment]
bon on a désactivé le systeme disfonctionnel de notif et ca devrais etre réglé
