### ISSUE TITLE
Feuille de route - correction orthographe

### ISSUE THREAD

**Issue by zorglubu** [HUB-HUmanBeing/SystemD#79]
Deux petites coquilles à corriger dans la rubrique "Feuille de route".
1ère PHASE 2ème item : utilisateu**r** et non utilisateu**rr**
2ème PHASE : dernier item - mettre un s à carte**s**

Bien amicalement.
![feuille_route](https://user-images.githubusercontent.com/31647352/68596755-0562ed00-049c-11ea-9a19-178e72c28bf7.png)

**Comment by robinBanquo** [comment]
ca a été traité :) merci à toi @zorglubu de nous l'avoir fait remonter ;)
