### ISSUE TITLE
bugReport : Un bug sur la sauvegarde des items de la checklist...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#84]
#### content :
Un bug sur la sauvegarde des items de la checklist des taches. 
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/LjGhnwPGWjvurZR3X/calendar
> size : 1760 x 856
> locale : en-US

**Comment by robinBanquo** [comment]
ca sera pushé en prod en meme temps que le tableur
