### ISSUE TITLE
bugReport : "The  activity has been set on the calendar" appar...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#86]
#### content :
"The  activity has been set on the calendar" apparait autant de fois que l'on clique
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/LjGhnwPGWjvurZR3X/tasks
> size : 1760 x 856
> locale : en-US

**Comment by robinBanquo** [comment]
c'est bon ca non déja ? @ioqt00 ?

**Comment by robinBanquo** [comment]
je ferme l'issue, je crois que la modif sur la facon d'ajouter des events suffit a regler le bug
