### ISSUE TITLE
Calendar: bug avec l'heure de début, si je déplace la tâche et qu'elle chevauche l'heure actuelle, elle disparait/refuse de bouger.

### ISSUE THREAD

**Issue by ioqt00** [HUB-HUmanBeing/SystemD#89]

**Comment by ioqt00** [comment]
De plus, si je coche "recurring" et que la tâche est en cours, elle disparait du calendrier

**Comment by robinBanquo** [comment]
grossomodo c'est un probleme general avec la récurence des events

**Comment by robinBanquo** [comment]
réglé, ca arrivera en prod quant la branche "table" aura été poussée en prod
