### ISSUE TITLE
suggestion : Est il possible d'avoir un lien web direct vers un...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#92]
#### content :
Est il possible d'avoir un lien web direct vers un espace projet ... un lien qui permet de voir les contenus ... sans forcément pouvoir contribuer ? Un lien qui permet d'être ajouter sur une documentation de projet ... suis je clair ?

**Comment by ioqt00** [comment]
Ça peut se faire, c'est une bonne idée d'après moi. 
Comment tu verrais ça ? Un lien pour voir tout le projet (forum/calendrier/fichiers) ou juste une partie ?  Ou un moyen plus complexe pour choisir ce que tu veux montrer  ? Ou une section du projet destinée à recevoir seulement la "vitrine" du projet ?

**Comment by robinBanquo** [comment]
Dans cette première phase de system-d.org, il n'y a pas d'interaction possible avec un projet si l'on est pas membre. Avec les phases 2 et 3 par contre, on pourra en effet aller voir la page de présentation d'un projet et entrer en contact avec lui

**Comment by robinBanquo** [comment]
A l'heure actuelle, le chiffrement rends impossible de visiter un projet " en lecture seule"
