### ISSUE TITLE
création de marqueur carte : le panneau a droite est vide

### ISSUE THREAD

**Issue by robinBanquo** [HUB-HUmanBeing/SystemD#93]
quant on crée un marqueur de carte, on est censé avoir le panneau de droite qui s'ouvre avec le détail du marqueur mais il n'apparait pas (ca s'ouvre mais c'est tout noir)

**Comment by ioqt00** [comment]
En fait il est résolu du coup ce bug, juste encore actif sur le projet Sandbox parce qu'il est vieux!
