### ISSUE TITLE
Suppression de projet: supprimer les données associées.

### ISSUE THREAD

**Issue by ioqt00** [HUB-HUmanBeing/SystemD#95]

**Comment by robinBanquo** [comment]
je comprends pas? ca fonctionne pas les fonctions de delete recursifs des topics, commentaires, marqueurs de cartes etc ?

**Comment by ioqt00** [comment]
C'était une erreur de ma part, mais en fait les notifications restent en mémoire après la suppression, c'est fait exprès ? Et l'avatar des projets supprimés restent en Session aussi

**Comment by robinBanquo** [comment]
ah oui, il faudrait rajouter une ligne pour remove les notifications dans le code
server/classMethods/ProjectMethods/ProjectEditMethod.js

`ligne 76 :   ProjectNotifications.remove({projectId: currentProject._id})`

ah et sans oublier d'importer la collection au début du fichier

` import ProjectNotifications from "../../../lib/collections/ProjectNotifications";`

**Comment by robinBanquo** [comment]
après pour l'avatar en session c'est pas bien grave... toute facon il existe plus dans le serveur d'assets normalement

**Comment by robinBanquo** [comment]
je m'en occupes ce soir si tu l'as pas fait dans la journée
