### ISSUE TITLE
bugReport : Bonjour,
je n'ai plus accès à mes projets mon navi...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#96]
#### content :
Bonjour,
je n'ai plus accès à mes projets mon navigateur m'affiche en permanence "Project information deciphering".
comment puis-je resoudre le pb pour accèder à mes projets.
merci d'avance.
sandra.garnier@santepubliquefrance.fr
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
> appVersion : 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/TT9XQq7M6uNDcTMvM/tasks
> size : 1536 x 723
> locale : fr-FR

**Comment by ioqt00** [comment]
Mail envoyé pour tenter de récupérer plus d'informations, je ne suis pas arrivé à reproduire le bug sur Safari

**Comment by robinBanquo** [comment]
Tellement chiant les safaristes... J'ai rien pour bosser dessus

**Comment by ioqt00** [comment]
Attends un peu y a les Edgiens qui arrivent :')

**Comment by ioqt00** [comment]
Bonjour Clément,
 je n'ai pas l'impression d'avoir fait quelque chose de particulier... je n'ai pas supprimé de projet, par contre j'ai créé 2 projets que j'ai alimenté (sans envoyer de lien à personne puisque pour l'instant je voulais tester) et à la connexion suivante, j'ai eu le message indiqué ce matin. 
Je dis connexion, mais je ne me déconnecte pas, j'utilise le raccourci de mes favoris.
Je ne sais pas si cela vous donne tellement plus d'info...
Bonne journée
Sandra
==================

En y repensant, j'ai peut-être bien effacé le projet sur lequel j'avais été invité pour avoir accès à l'appli... Voici le lien reçu à toutes fins utiles :
https://www.system-d.org/invitation/pwcfrih8hJWERWDXD?password=huZ5UiSkwmpk7BHh5wgisMosVqbDduzTExAS4

bonne journée
Sandra

**Comment by robinBanquo** [comment]
est-ce que quelqu'un arrive à le reproduire ce bug en prod ou en local ? ouais, merci @aboire  j'avais pas tilté que c'etait un chrome...
jusqu'ici je n'ai jamais eu aucuns pb avec chrome de ce genre...

**Comment by robinBanquo** [comment]
Merci @aboire j'avais pas tilté que c'etait chrome, mais en effet : 
http://useragent.fr/?string=Mozilla%2F5.0+%28Windows+NT+6.1%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F78.0.3904.97+Safari%2F537.36

Je suis incapable de reproduire le bug qu'elle à eu... jusqu'ici j'ai jamais eu ce probleme avec chrome...

**Comment by robinBanquo** [comment]
Suite à mon précédent message :
la même chose se produit si j'essaie de créer un nouveau projet.
bonne journée

context info :
platform : Win32
userAgent : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
appVersion : 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
vendor : Google Inc.
url : https://www.system-d.org/project/PaBv3pq57pBwekfZG/params
size : 1536 x 723
locale : fr-FR

**Comment by ioqt00** [comment]
Pour le coup, je viens de penser que c'est peut être complètement le problème inverse de ce qu'il se passe avec les projets qui disparaissent de la project-list sur FF.
À cause du test                
 if (i === arrayOfObject.length - 1)  (l. 502 par exemple)
Et du fait que cet async ne se comporte pas en séquentiel.
Si il se produit la même chose pendant l'encodage, ça peut donner ce type de comportement, non ?

**Comment by robinBanquo** [comment]
euhhh... j'ai pas tout compris, tu m'expliquera ca de vive voix la prochaine fois qu'on se capte sur le chat.
ce soir je vais regarder si je peux pas faire un truc sur le async foreach pour qu'il range les résultats du chiffrement/déchiffrement dans le meme orde, je crois que je vais passer par un objet intermédiaire genre : 
```
{
1: "res1",
2: "res2",
...
}
```
avant de le remettre sous forme de tableau derrière, ca prendra 20ms de plus à tout casser et on sera tranquille après

**Comment by ioqt00** [comment]
Non c'était débile, je pensait que encryptArray était appelé pour la liste des projets mais c'est pas le cas. 
Sinon une bonne vieille boucle for, c'est peut être un peu moins efficace mais ça a le mérite de marcher facilement et d'être lisible... En tout cas je suis là ce soir !

**Comment by robinBanquo** [comment]
@ioqt00 tu fera des essai avec for, mais je doute que tu ais de bons résultats en enchainant des fonctions asynchrone, tu auras les resultats dans le désordre je penses.
en vrai c'est galère parceque c'est vraiement super galère les boucles de fonctions asynchrone, et on va etre obligé d'avoir une solution "compliquée" je penses

**Comment by ioqt00** [comment]
En fait je pensais que l'asynchrone était ici un moyen d'augmenter les performances tout en travaillant en séquentiel, mais j'ai peut être loupé complètement le but. Du coup je voulais dire un boucle for à l'ancienne sans la partie asynchrone, en renvoyant la liste complète à la fin (ça permet d'éviter des tests à chaque itération au passage)

**Comment by robinBanquo** [comment]
ah non, c'est asynchrone parceque l'api de chiffrement d'un navigateur ne propose que des fonctions asynchrones... mais si on avait le choix, crois moi bien qu'on se ferait pas chier avec ca ^^, meme si ca coutais un quart de secondes a l'utilisateur ! :-)

**Comment by robinBanquo** [comment]
de toute facon, pour etre honnete, je dois avouer un truc : les temps de chiffrement sont volontairement un peu ralongés afin que l'utilisateur puisse voir et lire qu'il y a un chiffrement... c'est comme une voiture qui fait pas assez de bruit et ou on va faire quelquechose en plus pour lui donner "un bruit de bon fonctionnement" c'est un peu crapuleux mais bon ^^
