### ISSUE TITLE
bugReport : Suite à mon précédent message :
la même chose se p...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#97]
#### content :
Suite à mon précédent message :
la même chose se produit si j'essaie de créer un nouveau projet.
bonne journée
#### context info :
> platform : Win32
> userAgent : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
> appVersion : 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
> vendor : Google Inc.
> url : https://www.system-d.org/project/PaBv3pq57pBwekfZG/params
> size : 1536 x 723
> locale : fr-FR

**Comment by robinBanquo** [comment]
je delete pour le rajouter en comment de l'issue precedente
