### ISSUE TITLE
suggestion : Le changement de langue sur la page d'accueil n'es...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#98]
#### content :
Le changement de langue sur la page d'accueil n'est valable que sur la page d'acueil et ne modifie pas les paramètres de l'utilisateur.

**Comment by robinBanquo** [comment]
c'est vrai que si on est connecté, ca pourrais aussi changer les options de l'utilisateur en meme temps, chouette suggestion

**Comment by robinBanquo** [comment]
ca a été réalisé, merci pour la suggestion, ca sera sur la prod bientot
