### ISSUE TITLE
bugReport : Par moment, le menu user ne veut pas apparaitre lo...

### ISSUE THREAD

**Issue by systemDBugReport** [HUB-HUmanBeing/SystemD#99]
#### content :
Par moment, le menu user ne veut pas apparaitre lorsque je clique sur la flèche
#### context info :
> platform : Linux x86_64
> userAgent : Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> appVersion : 5.0 (X11)
> vendor : 
> url : https://www.system-d.org/project/vEgHeiK2s6oXDrqcN/forum/?mainTopic=true&topicId=P75nbcKyzoSL3nTys
> size : 1760 x 856
> locale : fr-FR

**Comment by robinBanquo** [comment]
c'est lié à une petite fonction materialize qui ne se lance pas au bon moment( le menu ne doit pas etre encore dans le dom au lancement de la fonction )  il faudrait peut etre mettre un settimout dessus (et reperer ou elle se cache aussi)

**Comment by robinBanquo** [comment]
client/templates/includes/menu/menu.js ligne 73....
ralonger le timout devrais marcher, ou, plus salement, la relancer 3 secondes apres "au cas ou" )
